#!/usr/bin/env bash

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    unlink "$HOME/$folder" 2> /dev/null
    stow $folder
done
popd

# executable files
find ~/.local/scripts/ -type f -iname "*.sh" -exec chmod +x {} \;
